# Remember to pass --service-ports to publish ports and make the server accessible on port 8787
# For use with digital ocean droplets

version: "3.8"
services:
  rstudio:
    image: shrabastee/r-causalverse
    ports:
      - 8787:8787
    volumes:
      - type: bind
        source: ~/home/ec2-user/Finance_shiny
        target: /home/rstudio/data
    environment:
      - PASSWORD=Montecito
      - TZ=America/New_York
    tty: true
    restart: always
